#########################
# Okyanus Configuration #
#########################

# Displays more output on the command line
debug = false

[chat]

# Default chat message format
# First %s is the player name,
# Second %s is the messsage.
# Color supported with the ยง character.
defaultFormat = "<%s> %s"